import os
import re
from typing import Any, Dict, Optional, Pattern

from ..file_comparator.factory import ComparatorFactory


def _detect_file_type(file_path: str) -> str:
    """Auto-detect comparator type from file extension."""
    ext = os.path.splitext(file_path)[1].lower()
    _type_map = {
        '.h5': 'h5', '.hdf5': 'h5', '.hdf': 'h5',
        '.json': 'json',
        '.csv': 'csv', '.tsv': 'csv',
        '.xml': 'xml', '.html': 'xml', '.htm': 'xml',
        '.txt': 'text', '.log': 'text', '.out': 'text', '.py': 'text',
    }
    if ext in _type_map:
        return _type_map[ext]
    # For unknown extensions, use binary comparator
    return 'binary'


class Assertions:
    @staticmethod
    def equals(actual: Any, expected: Any, message: str = "") -> bool:
        if actual != expected:
            raise AssertionError(f"{message} Expected: {expected}, but got: {actual}")
        return True

    @staticmethod
    def contains(container: str, item: str, message: str = "") -> bool:
        """
        Check if the item is contained within the container string.
        This method returns True if the item is found anywhere within the container,
        even if the container contains other information.
        """
        if item not in container:
            raise AssertionError(f"{message} Expected to contain: {item}")
        return True

    @staticmethod
    def matches(text: str, pattern: str, message: str = "") -> bool:
        if not re.search(pattern, text):
            raise AssertionError(f"{message} Text does not match pattern: {pattern}")
        return True

    @staticmethod
    def return_code_equals(actual: int, expected: int, message: str = "") -> bool:
        if actual != expected:
            raise AssertionError(f"{message} Expected return code: {expected}, got: {actual}")
        return True

    @staticmethod
    def compare_files(
        actual_path: str,
        baseline_path: str,
        file_type: Optional[str] = None,
        workspace: Optional[str] = None,
        **comparator_kwargs: Any,
    ) -> bool:
        """
        Compare two files using the appropriate file comparator.

        :param actual_path:   Path to the file generated by the test command.
        :param baseline_path: Path to the golden / reference file.
        :param file_type:     Comparator type ('h5','json','csv','xml','text','binary').
                              Auto-detected from file extension if omitted.
        :param workspace:     Working directory; both paths are resolved relative to
                              this directory when they are not absolute.
        :param comparator_kwargs: Extra keyword arguments forwarded to the comparator
                                  (e.g. ``rtol=1e-5``, ``atol=1e-8``, ``encoding='utf-8'``).
        :return: True when files are identical.
        :raises AssertionError: when files differ or an error occurs during comparison.
        """
        # Resolve paths relative to workspace
        if workspace and not os.path.isabs(actual_path):
            actual_path = os.path.join(workspace, actual_path)
        if workspace and not os.path.isabs(baseline_path):
            baseline_path = os.path.join(workspace, baseline_path)

        # Auto-detect file type from extension
        if not file_type:
            file_type = _detect_file_type(actual_path)

        try:
            comparator = ComparatorFactory.create_comparator(
                file_type,
                verbose=True,  # always include diff details in the assertion message
                **comparator_kwargs,
            )
            result = comparator.compare_files(actual_path, baseline_path)

            if result.error:
                raise AssertionError(
                    f"File comparison error ({actual_path} vs {baseline_path}): {result.error}"
                )

            if not result.identical:
                detail_lines = [str(result)]
                raise AssertionError(
                    f"File comparison failed ({actual_path} vs {baseline_path}):\n"
                    + "\n".join(detail_lines)
                )

            return True

        except AssertionError:
            raise
        except Exception as exc:
            raise AssertionError(
                f"File comparison error ({actual_path} vs {baseline_path}): {exc}"
            )